theme: jekyll-theme-minimal
google_analytics: 

title: Vasniktel's projects
description: Here is a showcase of my projects

show_downloads: false

projects:
  - name: My Playlist
    description: Интернет радио плеер для PSP
    url_repo: https://github.com/Vasniktel/My-Playlist
    url_downloads: https://github.com/Vasniktel/My-Playlist/releases/latest
    url_info: https://raw.githubusercontent.com/Vasniktel/My-Playlist/master/CHANGELOG.md
