theme: jekyll-theme-minimal
google_analytics: 

title: Vasniktel's projects
description: Here is a showcase of my projects

show_downloads: false

links:
  - name: My Playlist
    url_repo: https://github.com/Vasniktel/My-Playlist
    url_downloads: http://vasniktel.pp.ua/mypls/
    info: >
       ### Изменения \[18.11.16](3.14):

       - Весь контент программы размещается по центру страницы.
       - На фоне теперь обычный цвет вместо картинки. Это позволяет программе работать быстрее.
         Вы можете вернуть старый фон. Загляните в файл *basic.css* в папке *css*, если хотите узнать детальнее.
       - Обновлён адрес станции "Громадське Радіо".

